name:        classy-prelude-conduit
version:     1.5.0
synopsis:    classy-prelude together with conduit functions
description: See docs and README at <http://www.stackage.org/package/classy-prelude-conduit>
category:    Control, Prelude
author:      Michael Snoyman
maintainer:  michael@snoyman.com
license:     MIT
github:      snoyberg/mono-traversable

extra-source-files:
- README.md
- ChangeLog.md

dependencies:
- base >= 4.10 && <5
- transformers
- bytestring

library:
  source-dirs: src
  ghc-options:
  - -Wall
  - -fno-warn-orphans
  dependencies:
  - conduit >=1.3 && <1.4
  - classy-prelude >=1.5.0 && <1.5.1
  - monad-control
  - resourcet
  - void

tests:
  spec:
    main: Spec.hs
    source-dirs: test
    dependencies:
    - hspec
    - classy-prelude-conduit
    - QuickCheck
    - conduit
